import type { Metadata } from 'next'
import './globals.css'
import NavigationServer from '@/components/navigation/NavigationServer'
export const metadata: Metadata = {
	title: 'EquipMinds',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html>
			<body>
				<NavigationServer />
				{children}
			</body>
		</html>
	)
}
